---
- hosts: webserver
  become: True
  become_user: root
  tasks:
    - name: Install Java 8
      yum:
        name: "*"
        state: latest
    - name: Installing OpenJDK
      yum:
        name: java-1.8.0-openjdk
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: tim
        image: "timjar3/pubrepo1:{{BUILD_NUMBER}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
